# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kasper Schou Telkamp
title: Enrolled as MSc Eng., Quantitative Biology and Disease Modelling
email: kasper.telkamp@gmail.com
website: https://telkamp7.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: telkaMpOG
github_username:  telkamp7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kstelkamp
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Mig og Luna.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Kasper and I am a 27 years old student. I am currently on the 2<sup>nd</sup> semester of my master studies. Furthermore, I live at Trørød Kollegiet in Vedbæk together with my wife and two daughters.
  
  I am most skilled in: <mark>Statistics</mark> and <mark>Mathematical Modelling</mark>.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: https://github.com/telkamp7
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Denmark
        caption: 2021 - Present
        sub_title: Master of Science in Engineering
        quote: >
          Founded in 1829 with the mission of creating value for the benefit of society, DTU is an international elite technical university where education, scientific advice, and innovation rest on a solid foundation of world-class research.
        description: |
          During my studies I have taken courses at both DTU and the University of Copenhagen. This have given me the opportunity to pursue my interest within immunology and bioinformatics, aswell as my interest within advanced statistics, deep learning, and mathematical modelling. 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DTU Compute
        link: www.compute.dtu.dk
        # link_text: compute.dtu.dk
        sub_title: Academic Student assistant
        caption: July 2020 - Present
        quote: >
          The purpose of the expert panel is to develop mathematical models to throw light on the spread of SARS-CoV-2 in Denmark.
        description: | # this will include new lines to allow paragraphs
            My main role was to develop and maintain a mathematical model that was used together with an ensemble of models to forecast the SARS-CoV-2 spread in Denmark, and investigate the effects of specific interventions.
   - title: Experience # Title for the section
     layout: list # Type of content section (list/text)
     content:
      - layout: left
        title: Ungfredensborg
        link: www.ungfredensborg.dk
        # link_text: compute.dtu.dk
        sub_title: eSport Coach
        caption: October 2017 - January 2019
        description: | # this will include new lines to allow paragraphs
            Coached a group of teenagers in the age of 13-17 in the first-person-shooter game Counter Strike: Global Offensive (CS:GO). Our weekly practice resulted in a first place in the national CS:GO youth school competition. Furthermore I was a key figure in organizing three big LAN events with 70+ participants for youngsters in Fredensborg Kommune.
   - title: Experience # Title for the section
     layout: list # Type of content section (list/text)
     content:
      - layout: left
        title: Humlebæk Lille Skole
        link: www.hbls.dk
        # link_text: compute.dtu.dk
        sub_title: Substitute teacher
        caption: August 2016 - June 2018
        description: | # this will include new lines to allow paragraphs
            Handled two maternity leaves and worked as a day-to-day substitute teacher.
   - title: Experience # Title for the section
     layout: list # Type of content section (list/text)
     content:
      - layout: left
        title: Salling Group
        link: www.sallinggroup.com
        # link_text: compute.dtu.dk
        sub_title: Team coordinator
        caption: August 2015 - August 2016
        description: | # this will include new lines to allow paragraphs
            Daily operation of the bakery and general management of the service department in føtex Kokkedal. I took on responsibilities such as: recruitment, product planning and conflict management.    
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
